### ISSUE TITLE
About preview layout

### ISSUE THREAD

**Issue by GHLandy** [gruehle/MarkdownPreview#97] opened 2016-10-12 11:47 UTC
I have tried MarkdownPreview setting, but can't edit on left preview on right (default edit on top, preview on bottom). Is there anyway make it? And tell me, please. Thanks a lot.

**Comment by naher94** [comment] 2017-02-06 03:03
I agree it would be great to have a left|right split option as well

**Comment by pvarela** [comment] 2017-02-28 17:51
I'd also love to have that layout option too.

**Comment by burtondev** [comment] 2017-03-24 01:40
I took a look at the current version of Bracket's API, and it seems like the only configuration possible for the panel is at the bottom: [http://brackets.io/docs/current/modules/view/WorkspaceManager.html](url)

So it seems that extension developers are at the mercy of Bracket's API in this regard :-(

I have figured out a workaround if you **really** want to have the layout on the side: simply open a separate instance of Brackets, dock one to the left, the other to the right, and hide the Side Bar in the instance on the right (in Windows, you can dock or "split" applications using the shortcut Windows+arrow keys). Make sure that in the instance with Markdown Preview activated, you resize the preview pane vertically to cover the file view.

And voila! You will have the layout you desire, but you will lose linked scrolling. This isn't too bad because you can simply hover over each page and scroll to your desired position.

Hope you find this helpful!

**Comment by ezequias** [comment] 2017-03-24 18:35
@burtondev It could work but only if windows where sync. 

Nice try.

Ezequias

**Comment by john-cj** [comment] 2017-05-20 21:53
@burtondev Isn't this issue a duplicate of https://github.com/gruehle/MarkdownPreview/issues/31?

If it really duplicate, then it should be noted, that currently it seems Brackets *have* support for side preview.

> Vertical split is now supported in Brackets, see [here](https://github.com/adobe/brackets/pull/11820), please add support for it in this addon.
> *mxxrten*

Though, I haven't really tested it.

**Comment by khatastroffik** [comment] 2017-07-30 12:36
afaik: 
The _split view_ (vertical or horizontal) functionality allows to open one single document in two editor panes (the split panes).

Hence:
* Those split panes are for **editing** purpose only.
* SPLIT = the original single editor pane is divided in 2 (sub-)panes but those 2 aren't able to separately manage their own additional panels like the markdown preview panel, which is instantiated using `WorkspaceManager.createBottomPanel(...)`: The editor panels (either single or split) don't own the bottom panel.
*  the 2 split editor panels should not (cannot?) be misused to _inject_ a preview panel into one of them. It would be a breach in brackets consistency/functionality (e.g. synchronization of the 2 editors  ...)!

A possible (and feasible, as demonstrated by the asciidoc preview extension) solution is to implement a "_detaching the bottom panel and display it in a standalone window_" functionality. Such a standalone window could then be positioned anywhere... 
Another solution would consist in modifying the code of brackets itself... 😉

**Closed as completed** 2018-02-14 13:47 UTC
